[tool.poetry]
name = "alchemy-tuto"
version = "0.1.0"
description = ""
authors = ["Joan Vasquez <dev.joanvasquez@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
SQLAlchemy = "2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
